version: '3'

services:
  database:
    image: postgres
    restart: unless-stopped
    container_name: 'database-dg'
    environment:
      - POSTGRES_DB=dg-database
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password123
    ports:
      - '5432:5432'

  redis:
    container_name: "redis-dg"
    image: redis:alpine
    restart: always
    ports:
      - '6379:6379'